name: truetalk_proto
description: "Прототип проверки фактов"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  speech_to_text: ^7.4.0  # ✅ Новая версия с поддержкой новых API
  html: ^0.15.6
  flutter_dotenv: ^6.0.1
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - .env